name: Trigger auto sync
on:
  workflow_dispatch:
  push:
    branch:
      - qa
      - TES-1829

jobs:

  generate:
    uses: katalon-studio-samples/testops-sync-script-repo-action/.github/workflows/generate-repo-metadata.yml@main
    with:
      repository-name: healthcare-tests
      testops-base-url: ${{ inputs.testops-base-url }}
      branch: qa
    secrets:
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      token: ${{ secrets.TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Trigger TestOps auto sync
      #   run: |
      #     curl \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     https://api.github.com/repos/katalon-studio-samples/testops-sync-script-repo-action/actions/workflows/staging.yml/dispatches \
      #     -d '{"ref":"main"}'

      #     curl \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     https://api.github.com/repos/katalon-studio-samples/testops-sync-script-repo-action/actions/workflows/qa.yml/dispatches \
      #     -d '{"ref":"main"}'

      - name: Checkout main
        uses: actions/checkout@v3
        with: 
          path: target-repo

      - name: Scan repository
        uses: katalon-studio-samples/testops-sync-script-repo-action@main
        with: 
          path: target-repo
          github-url: https://github.com/katalon-studio-samples/healthcare-tests
          testops-base-url: https://testops.qa.katalon.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          token: ${{ secrets.TOKEN }}